##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [26]:
import numpy as np
ar1=np.random.randint(1,8,7)
print(ar1)
print("eleman sayisi",ar1.size)
print("boyut",ar1.ndim)

[4 1 3 5 6 6 4]
eleman sayisi 7
boyut 1


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [60]:
arr2=np.array([[1,2,6,7],[4,3,9,5]])
print(arr2)
print("boyut",arr2.ndim)
print("eleman sayisi",arr2.size)
print(arr2.shape)
arr3=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
print(arr3)
print("boyut",arr3.ndim)
print("eleman sayisi",arr3.size)
print(arr3.shape)

[[1 2 6 7]
 [4 3 9 5]]
boyut 2
eleman sayisi 8
(2, 4)
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
boyut 3
eleman sayisi 12
(2, 2, 3)


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [47]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
arr5=np.array([[1,2,6,7],[4,3,9,5]])
print(arr5[0][1])



2


In [48]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
arr6=np.array([[1,2,6,7],[4,3,9,5]])
print(arr6[0][3])


7


In [50]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
arr7=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
print(arr7[1][1][2])


9


In [51]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
arr8=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
print(arr8[0][0][1])


5


##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [43]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
arr9=np.array([[1,2,6,7],[4,3,9,5]])
print(arr9[0][1:3])


[2 6]


In [44]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
arr10=np.array([[1,2,6,7],[4,3,9,5]])
print(arr9[1][1:])

[3 9 5]


In [45]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
arr11=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
print(arr11[0][1][0:])

[21  8 11]


In [46]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
arr12=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
print(arr12[1][0][1:])

[ 6 20]


##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [38]:
arr13=np.ones(15,dtype=int).reshape(5,3)
print(arr13)
arr14=np.zeros(15,dtype=int).reshape(5,3)
print(arr14)
print("satir bazinda birlesme\n",np.concatenate([arr13,arr14],axis=0))
print("sutun bazli birlesme\n",np.concatenate([arr13,arr14],axis=-1))

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
satir bazinda birlesme
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
sutun bazli birlesme
 [[1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]]
